version: "3"
services:
  nodejs-app:
    build: .
    container_name: my-nodejs-app
    ports:
      - 8000:8000
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data:
